### ISSUE TITLE
Trakt manager "add to collection" not working

### ISSUE THREAD

**Issue by denimnani** [nixgates/plugin.video.seren#101]
Hey Nix,
The function on trakt manager  "add to collection" is not working for both movies and tv shows.
I receive the confirmation notification but nothing new is added to collection.
The "add to watchlist" is working fine.
I have tried in diferent days and devices to rule out any trakt issue but it seems to be seren.

**Comment by nixgates** [comment]
I've identified an issue, if Seren has not seen any of the episodes for the show it's likely it won't be marked as collected. 

Seren will need to ensure an episode is available in the database to successfully add to collection or force a relative sync of the database.

**Comment by nixgates** [comment]
@denimnani I assume they appear after a few minutes though?

I've added a force sync to happen on the event these context menu items are triggered. This should mean the items are updated straight away and don't wait for the next background sync.

**Comment by denimnani** [comment]
No Nix,
The problem is that the itens never appear in the collection or in the trakt web site, even after a few hours.
I have tried to sync after adding to collection but still noting, the watchlist is work almost immediately.

**Comment by DJMix-I-Can** [comment]
I believe this might be relevant to what I'm going through. I was on 0.1.35 because it was working fine & saw that a lot of people were having problems on the updates. Once the updates started fixing their issues, I decided to update my setup. It was working fine until I added a new show called Dead To Me & the new season of Deep State & Tales came out. Neither of them appeared on my Next Up.  I went to Trakt Sync Tools and Force Synced Activities and Rebuilt the Database. I rechecked Next Up & the Second Season of Deep State appeared but not the new show Dead To Me or the second season of Tales. When I went to check my collection, their in there. I went to TVDB and noticed that the second season of Tales wasn't in there but the new show Dead To Me was. The new show should've popped up but I understand why Tales didn't.  Another thing I should mention, while the database was half way through of rebuilding, I received another notification about syncing Trakt. I cancelled it because one was already in progress.  
In Exodus Redux and 13 Clowns everything showed up besides Tales because it wasn't on TVDBs' database.  
I do appreciate the work you put into this but once you changed the Trakt structure you've encountered a lot of problems. Can you have an option for users to choose on how they want Trakt to work. They could choose the Exodus fork version or your Seren version.  I've always felt this has been the biggest issue with Seren, the way Trakt works with it. For the mean time, I'm going to roll back to 0.1.35. 
Thanks.

**Comment by denimnani** [comment]
@nixgates is working.
Thanks man
