### ISSUE TITLE
Library migration

### ISSUE THREAD

**Issue by Jezze83** [nixgates/plugin.video.seren#106]
@nixgates is there library migration function with seren from trakt? If so, how to do that? If not, is it possible add that function?

**Comment by nixgates** [comment]
Seren does not provide any library integration and I do not intend to add this feature moving forward.

Seren creates it's own local database of your collection/watched items from Trakt so adding library integration would only double up this information.

If there are features from the Kodi library that you would like to implement into Seren I'd be happy to look into doing it.

**Comment by pencey** [comment]
> If there are features from the Kodi library that you would like to implement into Seren I'd be happy to look into doing it.

Some skins offer a "global search" See BINGIE Mod. I'm using AuraMod right now since the global search is effectively useless for me since it's only good for Library content and Seren is basically the only thing I use. I'm not sure if there is a way for you to do this, or if it would have to be more on the skin side, but you did great with the NextUp feature so here's to hoping lol. Thanks!!

Here's the demonstration.
[https://vimeo.com/325814450](url)

**Comment by drinfernoo** [comment]
@pencey It's completely outside of Seren's scope to integrate with Global Search... In Arctic Zephyr 2, you can define custom add-on paths for the built-in skin search, which works really well with Seren and other add-ons.

**Comment by pencey** [comment]
Thanks for the tip!
