### ISSUE TITLE
Seren page item limit doesn't work for trakt lists

### ISSUE THREAD

**Issue by Shokaze** [nixgates/plugin.video.seren#138]
Hello, I wanted to check if i'm having a bug on my side or if this is a nixgate decision regarding the display of trakt personal lists. I've found some interesting trakt lists recommendation on reddit and decided to add them to my profile. However some of them have 200+ movies in it and now if i want to check them trough seren it takes forever to load the items in it.

What's weird is that i checked in seren settings that the page item limit is set to default 40 but this doesn't seem to apply to trakt lists, only for seren regular sections.

So do i have missed something or is it just the normal behaviour of seren regarding trakt lists' items display.

Thank your for the all the work provided into this great addon nonetheless !

**Comment by drinfernoo** [comment]
While it is a bit irritating for larger lists to take forever to load this way, I *do* believe it's intentional. The original reasoning behind the list limit was to cut down on Trakt requests, as the web service backends start to throttle requests after a certain number, but now that Seren is performing more caching of these requests (in the form of it's Trakt sync database), the limit is less of an issue once the content has already been cached.

@nixgates, maybe a setting to apply the limit to Trakt lists as well?

**Comment by Shokaze** [comment]
Yeah i did noticed that once seren cached the list itself, it is pretty fast to load it up next time. My doubt is that i imagine seren to have a cache size limit (or does it ?) so if you check trough a lot of trakt lists in seren it can become tedious to have to wait 5min+ for each new list.
But i do understand the potential design choice of limiting requests and to avoid to throttle the trakt API. 

I still believe a dedicated setting like you suggested is the best solution so user can each choose their preferred method but if nixgates did that in order to preserve the overall experience of the Seren addon as a whole then i also understand :). Would be nice to hear @nixgates es position on the matter 😃 .

**Comment by lukehansford** [comment]
The latest releases trakt list from gildad & Alex takes ages to load everytime Kodi loads. It is the last widget to load when all the other sections such as Trending load fine.

Is this because the limit of 40 is not being applied to our trakt lists so they are taking forever to load?

It would make sense they have the same limit and load at the same speed as Seren's other sections. People can increase the limit but 40 seems more than enough. 

This list is not loading in Seren. 

https://trakt.tv/users/pixelhunterprime/lists/netflix

Some trakt lists have 800+ items.

**Comment by drinfernoo** [comment]
By increasing the limit above 40, you are actually likely to be *slowing down* Seren, since 40 items per is when TMDb starts to throttle requests.

That particular Trakt list is kept "short" because giladg periodically removes older movies from the list, but can be a bit of a wait time for me as well.

**Comment by nixgates** [comment]
@lukehansford 

Unlike most addon caches, Seren also uses a semi permanent cache (trakt sync databse). Once an item has been seen and the meta information has been loaded, Seren will not need to update it again unless Trakt identifies it as being updated.

Unlike most addons, this means menu speed caching is faster as most information is local and not relying on a 24 hour timeout for all information.

You should also note though, that the positioning of widgets within the menus will also affect the loading times. In example, the same trakt list sits at the top in my personal widget list and is also the first to load on my device.

**Comment by nixgates** [comment]
I've just performed a test on the Netflix list with the latest Seren update and while it does take a somewhat long time (2-3 minutes) for the list to initially load, it does in fact load and after the initial loading of that list, the time is reduced to a few seconds. All subsequent openings of the lists should actually be fairly fast unless there is a very substantial amount of changes.

Keep in mind, massive lists like this require a comparatively large amount of data to be sourced so if you have not encountered these items in any menu before, data must sourced for them.

I personally don't think there is much need to reduce the menu to 40 items again and I'm more than happy with those speeds. I agree the initial loading of a list for the very first time is somewhat slow, but we are dealing with several hundreds of items.
