### ISSUE TITLE
Custom Providers: localtitle always EN aliases empty in def movie()

### ISSUE THREAD

**Issue by Philps** [nixgates/plugin.video.seren#151]
When usingCustomer Providers, all trakt/tmdb information which are passed to the custom provider are in EN.

As per Wiki, i would expect that self.language would affect localtitle. Also aliases remain blank and cant be used.

class source:
    def __init__(self):
        self.priority = 1
		self.language = ['en'] <------------------------------- 
        self.domains = ['']
        self.base_link = ''
		self.search_link = ''

  def movie(self, imdb, title, localtitle, aliases, year):
<--------------------------------------------------------------------- localtitle always EN, Aliases remain empty!

**Comment by nixgates** [comment]
Currently Seren only has translations for the English language and therefore only operates within the English realm of things. While I have some parts ready for working within different languages, it's still a little way off. (If you have any multilingual support I'd be very appreciative of a language file translation)

The class variable language is not utilized by Seren and has been carried over from the exodus format of providers. Changing this variable will not affect the metadata you receive in the methods.

In regards to the aliases being a blank list, I've updated this for the next update. This was an oversight that hasn't been caught since the initial creation of the addon.
