### ISSUE TITLE
Finished moves showing in Finish Watching

### ISSUE THREAD

**Issue by baxter300** [nixgates/plugin.video.seren#162]
Around 80% of the movies I watch on Seren still show up in the Finish Watching menu, even if I make a point and skip through all the credits

**Comment by baxter300** [comment]
@drinfernoo yeah I’ve been doing that as a work around but I assumed that they showing up there once completed was a bug

**Comment by baxter300** [comment]
@drinfernoo is that a Trakt or a Seren limitation? If Trakt then I guess that means this should be closed

**Comment by nixgates** [comment]
@baxter300 when Seren polls Trakt for this information all it's looking for is paused points and unfortunately can't distinguish currently whether the item has been finished since then. 

There's some adjustments to the Trakt Sync database coming that will allow us to actually check and identify whether the information is old or not and I'll add that to the queue of things to be done! 

Good catch!

**Comment by nixgates** [comment]
Seren 2.0 allows hiding of watched items now. 

Closing
