### ISSUE TITLE
[REQUEST] sort by filesize or bitrate

### ISSUE THREAD

**Issue by shocker1185** [nixgates/plugin.video.seren#247]
Especially while using autoplay, it would be sweet if it sorted sources by file size or bitrate. 
It would also be cool if uncached sources of a higher bitrate were automatically added to transfer...
At least with cached sources,  can subtitle tracks be listed and/or preferred...language also.

Thanks!

**Comment by ReaLx3m** [comment]
You can already sort by filesize. The option is in settings>sort & filter>enable secondary filesize sort. By default it puts the largest files on top.
If you want smallest on top, after enabling filesize sort, open C:\Users\your user\AppData\Roaming\Kodi\addons\plugin.video.seren\resources\lib\modules and open getSources.py using text editor(like notepad++) and search for this line:
torrent_list = sorted(torrent_list, key=lambda k: k['size'], reverse=True)
Just change the reverse=True to reverse=False , and save the changes. 
Now you have smallest files on top. This combined with "Tertiary HEVC sort" can result with small files with great quality and mostly 5.1 sound.

**Comment by shocker1185** [comment]
Thanks for the response!

**Comment by roberestarkk** [comment]
I've been watching this topic for a while because, while it was very helpful to me to know how to modify the source code to get sort by filesize to be in the opposite direction, I was hoping it would be added as a setting so I didn't need to go and re-modify it every update.
Is that what's happened, or was this issue closed because reversing the sort order wasn't the original issue?

**Comment by roberestarkk** [comment]
The first one is what happened, I saw Seren had updated so I went and checked.
Huzzah! Many thanks
