### ISSUE TITLE
[REQUEST] Marquee-style side-scrolling display of long file names in stream source results

### ISSUE THREAD

**Issue by greenmr** [nixgates/plugin.video.seren#293]
The new 2.0.x stream source list layout looks great, but many release groups store files with very long names showing not only name, season, episode, etc, but also useful info for selecting which stream is best for you, such as included audio languages, audio and video compression codecs, and even the release group name. With the current layout of the stream source list long file names are truncated and much of this useful info about the source is not available to help in choosing which file to stream (or download). Displaying the file names with a horizontal scrolling action would allow the entire file name to be seen even with very long names. This could be a setting so the user could choose whether to side-scroll the results or not.

**Comment by peno64** [comment]
I would rather see the full name without having to scroll. Maybe multi-line or auto-scroll

**Comment by Maximus97** [comment]
Multiline or bigger box, but please no autoscroll.

**Comment by nixgates** [comment]
@Maximus97 @peno64 @greenmr 

This has been addressed and will be in the next update, just a slight shuffle of text position so the source file name is much longer now

**Comment by nixgates** [comment]
@peno64  @Maximus97 @greenmr I've released the update, could you please check and confirm you're happy with the changes?

**Comment by Nuklear92** [comment]
@nixgates I've already checked with 2.0.10 and it looks worse now. The font size is huge.😫 Hence, this is with the Default Estuary Kodi Skin. I hope whenever you're working with the Seren UI you're basing it for the Default Kodi skin and not a third party skin. 


![image](https://user-images.githubusercontent.com/76958541/103780653-448ac080-5003-11eb-863a-31ddb3ab08c5.png)

**Comment by Maximus97** [comment]
I have the same issue as @Nuklear92

**Comment by Nuklear92** [comment]
@Maximus97 @nixgates Good, so it's not only myself. I hope Nix gets a quick fix for this one, because now we can barely read half of the link names. 😢

**Comment by peno64** [comment]
Indeed, I have this also. I thaught I had not yet the latest version and would have looked at it further this evening but this confirms it...

**Comment by nixgates** [comment]
Bother, I must have left out the font size change. I'll change it again in the next update hold tight for me!

Sorry :(

**Comment by Nuklear92** [comment]
@nixgates no worries, I'm sure you'll fix it with the next one. Probably so many other bugs have been getting your head all over the place.😄 I'll keep an eye and give you a feedback once you push the next update out. 👍

**Comment by ljransom** [comment]
As requested from the duplicate ticket I raised, here's my experience using my titan binge build. Very large text for the file names so you can't read most of it. On kodi 18.9, and this issue wasn't present pre Seren 2.0.
![IMG_20210106_172755](https://user-images.githubusercontent.com/76923908/103823531-2ad09400-506a-11eb-8993-a63f7e6b8d0a.jpg)

**Comment by MagicFirefly** [comment]
Want to raise my hand on this as well. Linux CoreELEC, Kodi with 65" OLED display. Using the default Kodi Estuary skin with default font and zoom at 0%. After an item is scarped, the source select results do not allow a method to see the entire info line that may include info not shown elsewhere. Thanks

**Comment by SirRickie** [comment]
Same here. I'm using the Estuary Mod skin. Cannot see the entire info line.

**Comment by nixgates** [comment]
I've got another rendition coming through in next update if you guys wouldn't mind checking when released

**Comment by Nuklear92** [comment]
@nixgates Sure, I'll be waiting to give you a feedback as soon as I get the new update! 😃

**Comment by Nuklear92** [comment]
@nixgates As promised, told you I was going to give you a feedback regarding this issue as soon as the new update comes out which I already installed and using, 2.0.11. 

So, the issue seems to be fixed for the default Kodi Estuary skin. However for third party skins, in my case Arctic Horizon it kinda broke for sources that aren't highlighted in the second screenshot. Either way, I won't keep bothering you with this and just get used to using the SS UI like it's. You've gone through so much hassle lately, with the Trakt situation and all. So, I just wanted to give you the final feedback from the default Estuary skin and a third party skin perspective. 🙂

![Estuary Kodi Skin](https://user-images.githubusercontent.com/76958541/104682154-04da6d80-56c2-11eb-8348-0368e72f5826.jpeg)

![Arctic Horizon Skin](https://user-images.githubusercontent.com/76958541/104682161-09068b00-56c2-11eb-9f15-867c04175b3c.jpeg)

**Comment by nixgates** [comment]
@Nuklear92 try 2.0.12 :) I'm just pushing to the repo now

**Comment by MagicFirefly** [comment]
For Estuary, it's two thumbs up. If I had more thumbs, well... you'd get those too. Thanks!!

**Comment by Nuklear92** [comment]
@nixgates Now it looks better on Arctic Horizon! Thanks for fixing it.🤩 

Well I guess it's safe to close this issue, since now links can be easily read and nothing seems to be broken for now. 👍

![image](https://user-images.githubusercontent.com/76958541/104687953-29d4dd80-56ce-11eb-80ae-ce0394e5cc94.jpeg)

**Comment by nixgates** [comment]
> @nixgates Now it looks better on Arctic Horizon! Thanks for fixing it.🤩 
> 
> Well I guess it's safe to close this issue, since now links can be easily read and nothing seems to be broken for now. 👍

Closing it off! :)

**Comment by Maximus97** [comment]
Can we have the option to display two rows so all text is always displayed?
