### ISSUE TITLE
Progress circle not working on widgets

### ISSUE THREAD

**Issue by ivarbrandt** [nixgates/plugin.video.seren#297]
This has been an issue since before the 2.0 release. The progress circle that appears on half watched movies and tv shows works great within Seren but doesn't work on widgets used with Seren. This isn't a huge issue and I know there are far more important things to fix. I just wanted to bring it to your awareness. Thank you for all that you and your team does.

**Comment by Dealz-416LS** [comment]
+1 for this!

**Comment by nixgates** [comment]
@ivarbrandt unfortunately from my testing on some jurial skins, the skin is overriding this information by displaying the remaining episodes to watch instead of the in progress marker. 

This would need to be addressed by the skin developer unfortunately as Seren is providing this information correctly and can't manage how it's displayed.

I'm here if you need any help further but I am going to close this one off. Just comment here if you need me :+1:
