### ISSUE TITLE
Kodi Leia - NextUp episode marked as watched immediately

### ISSUE THREAD

**Issue by Mastacc** [nixgates/plugin.video.seren#32]
As soon as the next episode from NextUp starts playing it is marked as watched in Trakt immediately. It's only happening on Kodi 18. It's not doing that on Kodi 17.

**Comment by Mastacc** [comment]
Still happening, unfortunately. Skip to end of 1x01 --- > 1x01 marked watched at 10:03 PM ---> skip to end of 1x02 ---> 1x02 starts playing ---> 1x02 marked watched at 10:03 PM

**Comment by nixgates** [comment]
Yea I think it might be due to issue I had with the keep alive. Seems Kodi is retaining the position of the previous playing item for a few seconds when the next starts so when Seren sends time information to Trakt it's information from the previous episode.

I'll have a look and hopefully putting a delay on it should fix the issue.
