### ISSUE TITLE
Small adjustment request

### ISSUE THREAD

**Issue by G-streamer** [nixgates/plugin.video.seren#350]
Hate to complain, but I keep getting a pop up warning for "Unknown error connecting to trakt" which I assume is because I am not synced to a trakt account. I prefer to use Seren without trakt as I have no interest in maintaining a trakt library. I only use the Kodi library which is all I need. Is there any way to stop this popup?

**Comment by nixgates** [comment]
@G-streamer this is not due to you not having a Trakt account unfortunately. This is Seren letting you know that there was a failure to fetch information from Trakt, this could be information about a show, movie, episode or list. It's essentially feedback from Seren to say hey, somethings gone wrong and it's out of my control.

What I can do is instead of an ok dialog, I will make this a notification so it's not so much of an interruption and will show and disappear all on it's own.

**Comment by nixgates** [comment]
The change I mentioned should now be available in 2.0.10

**Comment by G-streamer** [comment]
Ah, I found it odd that it was happening with my Kodi just sitting idol an not using Seren. Thank you for your quick response and adjustment! Much appreciated as I know you are working your tail off chasing bugs. Careful you don't pull out ALL your hair. lol

**Comment by nixgates** [comment]
@G-streamer haha thanks. I'm doing ok now, its slowing up so more hair on my head now lol.

Closing it up.
