### ISSUE TITLE
[BUG] no Trakt update

### ISSUE THREAD

**Issue by deklica** [nixgates/plugin.video.seren#363]
**Describe the bug**
After episode watched, no Trakt update, episode is still have unwatched status... 
After few minutes I get this error log on pics 1-4, and on pause I get error like on pic 5.

**Screenshots**
![IMG_20210106_033414](https://user-images.githubusercontent.com/29065519/103798375-e33a1000-5049-11eb-88d4-f1cdf46ffe93.jpg)
![IMG_20210106_033433](https://user-images.githubusercontent.com/29065519/103798388-ea611e00-5049-11eb-9c1b-849885876477.jpg)
![IMG_20210106_033456](https://user-images.githubusercontent.com/29065519/103798361-dd442f00-5049-11eb-862e-8d5473e8cb0d.jpg)
![IMG_20210106_033519](https://user-images.githubusercontent.com/29065519/103798398-ef25d200-5049-11eb-84d8-77d0cafb87e8.jpg)
![IMG_20210106_174409](https://user-images.githubusercontent.com/29065519/103798382-e6cd9700-5049-11eb-80ae-5909a1b73dac.jpg)

**Kodi Version:**
 - Libreelec v9.2.6 (Kodi 18.9)
 - RPi4
 - Seren 2.0.9

**Comment by minhgi** [comment]
Seren 2.10 is released,  It might fix the track sync issue.

**Comment by nixgates** [comment]
@deklica as mentioned, this is likely fixed in 2.0.10, if you wouldn't mind double checking for me :)

**Comment by deklica** [comment]
There is no update in repository, but I updated manually...
No error showing up, but still episode is marked like unwatched (in Next Up, when I click stop 30s before end), and no Smart play pop-up on the end of the episode (must show 60s before end)...

**Comment by AshDroidG** [comment]
I can confirm this bug. Seems to be an issue with Seren either not storing trakt resume points or not using them. I believe a previous ticket created (#355 Items disappearing from Finish Watching movies list bug) is related to the same issue. Basically if I start watching a new movie and after 10 mins stop and check Finish Watching the movie is there however on Kodi restart the movie disappears from finish watching and I can resume the movie by searching it however it uses local resume points rather than trakt resume points. If I switch devices from laptop to TV I cant resume the movie it starts from the beginning.

**Comment by Fatal-Errol** [comment]
This also happens to me but is inconsistent. Sometimes it works, sometimes no. Sometimes I can see the progress in trakt but after the video finishes, it doesn't get tagged as watched in trakt and seren. Using 2.10, clean seren install.

**Comment by deklica** [comment]
Yes, randomly works or not... I deleted all dB files in addon directory, restarted, new database generated, and first time pop-up showed and watched mark works, but now, same like before, no pop-up and no tag as episode watched...

**Comment by ShibajiCh** [comment]
Hi,
Even I'm facing these exact same issues.

**Comment by nixgates** [comment]
Looks like @deklica log snippet that it's a time out issue with Trakt. I'm looking into changing up our timeouts for Trakt so support some slower connections.
