### ISSUE TITLE
[BUG] Unable to disable reuse Language Invoker

### ISSUE THREAD

**Issue by SerpentDrago** [nixgates/plugin.video.seren#372]
https://old.reddit.com/r/Addons4Kodi/comments/krrwr1/up_next_widget_crashing/gicaa8v/\\

Even manually editing xml and setting to false , causes seren upon startup to just set it back to true . and the shortcut in settings does not disable it . 

guy is having random crashes he needs to disable this . same as i have to do sometimes . This setting really really should NOT be enabled on windows imho .

**Comment by 123Venom** [comment]
Seems to toggle the setting fine in the addon.xml for me but the UI setting option does still claim **Enabled** when addon.xml did flip it to.... 
**<reuselanguageinvoker>false</reuselanguageinvoker>**
If one was to manually edit that I'd not remove that line, as you advised, the addon prob looks for it and just puts it back.  Better to edit it from **true** to **false**.  I think he's prob just believing it did not work because the UI setting still shows Enabled.

**Comment by nixgates** [comment]
@SerpentDrago fixed for next update (2.0.13) bud! :)

**Comment by nixgates** [comment]
@SerpentDrago closing this up, all fixed
