### ISSUE TITLE
Display/Interface after scraping (Source Select screen)

### ISSUE THREAD

**Issue by cg8440** [nixgates/plugin.video.seren#394]
Wonderful work with Seren addon and thanks for Seren 2.0. 

I have a suggestion for improvement. Can you please restore the Display/UI after scraping (Source Select screen) to the original? The recent change takes away lots of functionality and useful information. For example, the title gets cut off, and along with that, other information like whether the link is BD-Remux or HDR or 264/265 and who provided the remux.

I like to select the source manually using all that information, but with the new display format, I just can't view all that information. Moreover, I want to turn off the spoiler summary/description on right side of the screen, but do not see an option. 

I understand there must be a reason to implement the changes to source select UI, but can you please provide an option or setting to revert back to original display format for those who find that more useful?

Thanks again for your wonderful work.

**Comment by SirRickie** [comment]
I fully agree. Also it is not easy-view to select a source when scrolling the list.

**Comment by nixgates** [comment]
Please refer to bug #293 closing as duplicate.

@cg8440 next update has a slight modification for the source select view which will allow almost all titles to display the full release title.

If you would like to disable the information on the side I would suggest utilizing a different Seren theme that doesn't display that info.

It should also be noted that the info list now displays the encode's name AVC/HEVC instead of x264/x265 respectively.
