### ISSUE TITLE
[BUG] 2.0.12 - RD Cloud Scrapping not working for the Authenticated Account

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#413]
**Logs**

Please provide debug logs to assist with your issue

**Describe the bug**
I have cached a torrent of Naruto Shippuden into my account. In the Seren setings I enabled Scrapping RD cloud. But when the scrapping begins it goes through all the providers and returs no playable sources found and I feel scrapping not checking the RD cloud for the cached torrents.

**To Reproduce**
1. Cache a torrent in RD Cloud
2. Enable the RD Clound scrapping in Seren Settings.
3. Try to play the cached torrent from the Seren via Collection or Watchlist etc (Not from My Files)

**Expected behavior**
If the RD cloud scrapping is enabled the scrapping should first check the RD cloud and if Pre-emptive termination is enabled stop the scrapping immediately. 

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version - 18.9
 - Version 2.0.12

**Additional context**

**Comment by nixgates** [comment]
Can you please provide the filename of the file you are trying to play

**Comment by sathish804** [comment]
> Can you please provide the filename of the file you are trying to play

I was trying to play the first episode Home coming in the Naruto Shippuden. Attached is the screen shot of cached torrent of it in my rd cloud account. 

![Screenshot_20210115-155550](https://user-images.githubusercontent.com/14090242/104742182-6e9e5a00-574a-11eb-82c2-537f19cde2b1.jpg)

**Comment by nixgates** [comment]
@sathish804 this is more due to the fact that Seren doesn't really support anime items. While you do get lucky here and there, the way anime is structure (episode numbering, season numbering, etc) doesn't fit into the western norms. It's a pipe dream to get better anime support into Seren but it's not something that I intend to look at anytime soon unfortunately.

I'd suggest if watching Anime, to utilize an addon dedicated for it as they focus on that style.

**Comment by sathish804** [comment]
@nixgates Thank you!! I will check this for normal titles other than anime and let you know if its working or not.

**Comment by nixgates** [comment]
@sathish804 no worries! If you catch one let me know.
