### ISSUE TITLE
[BUG] Seren doesn't mark episodes as watched on Trakt after watching a show

### ISSUE THREAD

**Issue by H4wkeye1** [nixgates/plugin.video.seren#429]
As the title says, while watching an episode it will scrobble correctly to Trakt however upon finishing it will not mark the episode as watched on Trakt. It seems to be inconsistent and marking does work correctly on other similar addons. It also worked correctly prior to 2.0.

Using Kodi 18.9 and Seren 2.0.13 on a fresh, clean install. Reauthed Trakt.

Debug log files below.

https://paste.kodi.tv/ucuwubecam

**Comment by nixgates** [comment]
@H4wkeye1 try setting your mark watched percentage down a bit.

**Comment by H4wkeye1** [comment]
> 
> 
> @H4wkeye1 try setting your mark watched percentage down a bit.

Will do this after and report back.

**Comment by H4wkeye1** [comment]
@nixgates It doesn't let me set it below 80%. And it was already at 80%.

**Comment by nixgates** [comment]
> @nixgates It doesn't let me set it below 80%. And it was already at 80%.

I'm going to need a debug log of the playback to find the issue if you would please

**Comment by drinfernoo** [comment]
@nixgates Is the log he attached not adequate?

**Comment by ShibajiCh** [comment]
Hi @nixgates , I'm also facing this exact same issue like @H4wkeye1. Trakt scrobbles fine on playback but after watching the video it's not marked as watched in Trakt. Also I noticed that this mainly happens when we continuously play a video from start to end without forwarding or rewinding it in the middle. Prior to Seren 2.0.x it used to work perfectly. Also I'm not getting the "Up Next" Dialog pop-up at the end of the video. Please advise. Thanks!

**Comment by ShibajiCh** [comment]
Hi @nixgates, after checking in several devices I can now confirm that the video scrobbles correctly in Trakt but gets marked as watched in Trakt only after a delay of about 12-15 mins after the complete video playback ends. Kindly check and advise. Thanks!

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
