### ISSUE TITLE
Can Seren use the same clear logos & artwork as Realizer?

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#45]
The artwork for both the movie sections and TV shows in the new Realizer is amazing.

The clear logos load instantly and all the artwork has the name of the movie in the artwork.

Can we have an option to use this source?

If you compare the realizer list sections you will see in titan the clear logos are super fast to load as well as the artwork.

**Comment by nixgates** [comment]
I can look into it, are they not just using fanart.tv?

**Comment by nixgates** [comment]
Fanart Support has been added for next public release

**Comment by lukehansford** [comment]
The images appear from a fresh install of the Realizer addon. 

I didn't need to enter any API key.

What do you have to do in Seren to get it to show the same cover art and logos that load very fast?

**Comment by nixgates** [comment]
You do need to sign up for an API key from fanart.tv and enter the key into the accounts page of Seren's settings. 

The fanart.tv team specifically ask for this process.

Also note, because fanart.tv's services are rather slow, only clear logos and clear art and shown from them. Unfortunately their servers are just to slow to display fanart and posters from them.

I'm going to close this issue of now if you don't mind?

**Comment by lukehansford** [comment]
> You do need to sign up for an API key from fanart.tv and enter the key into the accounts page of Seren's settings.
> 
> The fanart.tv team specifically ask for this process.
> 
> Also note, because fanart.tv's services are rather slow, only clear logos and clear art and shown from them. Unfortunately their servers are just to slow to display fanart and posters from them.
> 
> I'm going to close this issue of now if you don't mind?

I have found out from the Realizer Dev that the addon is using an internal database so that clear logos load super fast.

https://www.reddit.com/r/Addons4Kodi/comments/asgvij/fanarttv_faster_loading_clear_logos/egvc8uv/?context=3
