### ISSUE TITLE
[BUG] re-use language invoker notification

### ISSUE THREAD

**Issue by RichardPIS** [nixgates/plugin.video.seren#457]
When I start Kodi up I'm getting the mentioned notification and the system freezes for 10 seconds.

I found this line in my log:

WARNING: CPythonInvoker(28, /home/richard/.kodi/addons/plugin.video.seren/seren.py): the python script "/home/richard/.kodi/addons/plugin.video.seren/seren.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6WindowE,N9XBMCAddon4xbmc7MonitorE,N9XBMCAddon4xbmc7MonitorE

 - Kodi Version 18.9 on a Linux laptop.
 - Seren 2.0.15

**Comment by nixgates** [comment]
@RichardPIS this should only happen once or on each update as Seren enforces your setting (assuming it's disabled).

This unfortunately can't be avoided due to the way Kodi implements it the feature.

If this is happening every startup please let me know but otherwise there isn't anything I can do about this, if you have it disabled for a good reason then leaving it like that will be fine, other wise you can enable it and it won't keep showing up every update.
