### ISSUE TITLE
Auto scraping next episode while watching

### ISSUE THREAD

**Issue by avsha114** [nixgates/plugin.video.seren#486]
Hi.
After the last update I'm having a weird issue.
While I'm watching an epiaode from a TV show,  I usually use the arrows to fast forward the intro and recap. After I fast forward the intro the episode works great for like 30 seconds until suddenly rhe it stops and seren srarts scraping the next episode.
I tried disabling Pre-emtive scraping. Didn't help.
After I go back to the episode list I can start the episode from the same moment it stopped and then everything works great.

**Comment by nixgates** [comment]
@avsha114 this unfortunately isn't caused by Seren as it doesn't handle anything playback wise like that. 

It's likely due to your advancedsettings.xml if set or a network issue. If you check your log, you'll likely find Kodi is unable to connect back to the file correctly and will throw and error. 

My suggestion, try testing different CDN's from your debrid provider and remove your advancedsettings.xml if applied.

**Comment by inb4after** [comment]
@avsha114 It's a Kodi based issue which occurs when the stream has stalled, ie. your network<->debrid service cannot keep up the stream or the stream was closed suddenly. 

If you're still getting this problem, could you test my PlaybackEndedDefaultAction mod and set "Default action if playback ended" to "Exit player". 

Then if it happens the next time, it might exit the player instead of scraping the next episode.

I stopped getting this issue recently and cannot reproduce anymore.

Add my repo source:

`https://inb4after.github.io/packages`

...to your file manager and install the repo zip. Then go to Seren addon, press update and choose the version you wish you update to, [2.0.16+PlaybackEndedDefaultAction]

After testing you can return to official Seren in the same update menu but choosing Nixgates instead.
