### ISSUE TITLE
[REQUEST] Add Re-Watch Shows to Next Up

### ISSUE THREAD

**Issue by leethax666** [nixgates/plugin.video.seren#542]
**Is your feature request related to a problem? Please describe.**
I would like to see shows I've finished, but am re-watching, on Next Up

**Describe the solution you'd like**
maybe another specifically named Trakt list, Re-Watch or something, that is included in Next Up and tracks your progress

**Describe alternatives you've considered**
I made a trakt list called Re-Watch I add stuff to, but I have to manually open it and it's annoying and doesn't track my progress. I realize I can unwatch the whole show on trakt but I don't like that, i like the data lol. 

**Additional context**
Thank you!

**Comment by Dealz-416LS** [comment]
Wanted to comment to confirm the issue with created lists not updating.

I recently created a list which hasn't updated on Seren since I created it.

**Comment by leethax666** [comment]
> Wanted to comment to confirm the issue with created lists not updating.
> 
> I recently created a list which hasn't updated on Seren since I created it, it also isn't even following the same sorting as Trakt.

I don't think we have a related issue

**Comment by Dealz-416LS** [comment]
Oh, you said

>I made a trakt list called Re-Watch I add stuff to, but I have to manually open it and it's annoying and doesn't track my progress.

Sounded like my issue, my mistake.

**Comment by drinfernoo** [comment]
Seren populates its "Next Up" menu based on the contents of your "Next Up" section on Trakt's website.

Rewatching is a feature of Trakt VIP, in which you can mark that you are rewatching a show, and it will appear in your Next Up again on Trakt. You can also remove a show from your history in order to reset the progress, in the instance that you are not a Trakt VIP member.
