### ISSUE TITLE
[REQUEST] Distinction between Anime and TV Shows.

### ISSUE THREAD

**Issue by MutennRoshii** [nixgates/plugin.video.seren#670]
**Describe the feature you'd like**

Instead of 2 categories (Movies & TV Shows), having 3 categories. I know you can sort by genre "Anime", but this won't let you select trending/popular lists. I apologize if this feature has already been requested.

**Describe alternatives you've considered**

I suppose there isn't a separate category because Trakt doesn't have it either. But SIMKL does, so maybe you could add SIMKL Support or add Anilist/MyAnimeList to the accounts. 

**Additional context**

**Comment by Goldenfreddy0703** [comment]
Honestly a great idea but i doubt seren will add them due to the work provided to add a category like that. Its probably best to stick with Kaito sense it was a fork of seren or was an idea based on seren. I heard the developer will be updating his add-on in a few days or in a week. There is an anime genre, the only downside is that it only has like 7 or 8 animes in the genre. 

If seren did add an anime section like with movie or tv show, there would have to be settings on what audio it needs or subtitles, and 30 sec intro skip, and end skip too, its honestly too much and i bet the developer would say no to this suggestion. 

I definitely think its a great idea tho, but sadly i think the developer is eventually going to say no to this in the future.

**Comment by AbdelkarimLamrini** [comment]
Yeah I now realize how much work that would take.
I just wanted to have all my shows + anime in one tracking service. I'll just continue with trakt+anilist.

**Comment by Goldenfreddy0703** [comment]
> 
> 
> Yeah I now realize how much work that would take.
> I just wanted to have all my shows + anime in one tracking service. I'll just continue with trakt+anilist.

Im not sure if it still exist but there is a trakt addon to keep up with your movies and shows, maybe that will help you

**Comment by Goldenfreddy0703** [comment]
No stale lol, this is a good suggestion in the future. 😂
