### ISSUE TITLE
Artwork issue with TMDb vs Fanart

### ISSUE THREAD

**Issue by ambulancePilot** [nixgates/plugin.video.seren#755]
This might not be a bug. I am just looking to further understand the artwork settings and how I can adjust them to produce the result I want.

Firstly, I pay for premium access to fanart.tv API which makes it slightly faster. So I don't have an issue using Fanart.tv API as the primary source for artwork. However, I generally prefer the style and quality of artwork from TMDb.

The issue I am having is actually when I change to TMDb as primary source, the season posters choices don't make any sense. It is clearly not selecting the poster with the highest number of votes. How does Seren pick which artwork to use when there are several choices and TMDb is set as primary?

Additionally, how does the sliding scale work? Does a higher number indicate higher priority? Lower priority? Why is the sliding scale there for some and not others?

Finally, what is the preferred artwork size for TMDb artwork? There are options for Fanart.tv however none for TMDb?

Thank you for the great addon! I much appreciate the work you have put in to it and I actually like the ability to fine tune settings (your addon has the most configurable settings of the similar addons). I just need a reference manual to understand what they do!

**Comment by drinfernoo** [comment]
So, a couple things here:

> Firstly, I pay for premium access to fanart.tv API which makes it slightly faster.

I don't know how much faster the API response is quantitatively, but Seren doesn't do anything special for this to work out, just so you know.

> It is clearly not selecting the poster with the highest number of votes.

Can you give an example? I have been watching Better Call Saul, so thought that might be a good example from my own usage:

![image](https://user-images.githubusercontent.com/2319508/166859846-413bd159-297b-4886-b2d9-f194de883817.png)

Now, I don't see a place where TMDb displays the votes on a particular image, but these seem fine to me:
* https://www.themoviedb.org/tv/60059-better-call-saul/season/1/images/posters
* https://www.themoviedb.org/tv/60059-better-call-saul/season/2/images/posters
* https://www.themoviedb.org/tv/60059-better-call-saul/season/3/images/posters
* https://www.themoviedb.org/tv/60059-better-call-saul/season/4/images/posters
* https://www.themoviedb.org/tv/60059-better-call-saul/season/5/images/posters
* https://www.themoviedb.org/tv/60059-better-call-saul/season/6/images/posters

> Additionally, how does the sliding scale work? Does a higher number indicate higher priority? Lower priority? Why is the sliding scale there for some and not others?

The "sliding scale" is the *number* of entries that will be kept for (and attached to) each item in Seren. The option exists for some and not others for what is technically an arbitrary reason, but were mainly chosen as many skins offer the ability to actually display multiple (random or otherwise) pieces of a single art type. Many skins will let you see multiple `fanart`, but most skins (none that I know of) don't have the feature to show different `clearlogo` art, for example.

> Finally, what is the preferred artwork size for TMDb artwork?

It depends on the setting. That setting (though it is under the Fanart.TV heading) affects both Fanart.TV *and* TMDb artwork. Thanks for bringing that to my attention... we'll make sure to move it to a more sensible spot in the settings next time they are reorganized!

For future reference, at this time, the sizes requested from TMDb are as follows:
| | Largest available | Medium | Small |
|:---:|:---:|:---:|:---:|
| `fanart` | `original` | `w1280` | `w780` |
| `poster` | `w780` | `w500` | `w342` |
| `keyart` | `w780` | `w500` | `w342` |
| `thumb` | `w780` | `w300` | `w342` |
| `icon` | `w780` | `w342` | `w185` |
| `cast` | `w780` | `w500` | `w342` |

These were chosen to be a good balance between what is actually offered by TMDb (as per their API docs, by making a call to `/configuration`, described [here](https://developers.themoviedb.org/3/configuration/get-api-configuration)), and what is actually usable and reasonable for Kodi. Admittedly, there are some inconsistencies, in that "Largest available" does not request `original` for *every* art type, but this is being looked at as an improvement for a future update of Seren as well.

> I just need a reference manual to understand what they do!

Funny you mention it... As of Kodi Matrix, the `settings.xml` definition actually supports built-in help texts for each setting, which have been discussed being added. Unfortunately, we aren't ready to do that, as it isn't supported on Leia, which Seren does still support. When Kodi gets closer to a stable Nexus release, we are probably planning to look into dropping Leia support and looking into the future!
