### ISSUE TITLE
[REQUEST] Browse Collection of Movies.

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#758]
I used to use Venom, and he had, in the CM menu a link called "Browse Collection" on movies that are part of a collection on TMDB. Like Batman, or the Split/Glass series and such
Very useful for us binge watchers.
You would simply right click a movie cover, and if it is a series of movies on TMDB, the button showed up in the CM and would put you in a folder with all of them.
Could we get this in Seren as well when you have time to code it? -shouldn't take long to do :) I believe the option is built right into the API there to use.

**Comment by drinfernoo** [comment]
Unfortunately, as Seren uses Trakt for it's main backend metadata source, there isn't a particularly efficient way for it to retrieve data about collections.

Most of those collections probably have an associated Trakt list, like this one: https://trakt.tv/users/chipmantech/lists/star-wars-movies?sort=rank,asc

You could like that list in order to access it inside of Seren, or (alternatively) use an addon like TMDbHelper to find the collection/list and play content via a Seren player file.

**Comment by TapMeDead** [comment]
@drinfernoo It was to avoid having to do things like that, that I suggested the easier option for users hehe.
But I see the issue, if you don't use TMDB API at all, of course.
Thanks for the reply :)

**Comment by drinfernoo** [comment]
Seren does leverage TMDb as *a* metadata source, but not the primary one. Trakt is used as the primary source, which doesn't return any collection data at all (that I'm aware of). The issue being, while the metadata is available *somewhere*, it would be pretty inefficient to retrieve, since the metadata would have to be collated based on results from both Trakt *and* TMDb.

**Comment by TapMeDead** [comment]
That is how I think Venom got it to work, he used a lot of crossover data, like you said it, both Trakt and TMDB.
I was hist beta tester for a short while before he closed down.
It does create some issues if you use both trakt and tmdb data together, because one or the other wont accept NONE as a failure, or something like that, I know we chatted about that, him and me, but most of it went over my head, me just being a user and all, not a coder hehe.

**Comment by TapMeDead** [comment]
I can live without the Collections, again, many thanks for replying and explaining it so even I can understand why it wont work well in Seren :)
