### ISSUE TITLE
seren playback crashes kodi

### ISSUE THREAD

**Issue by sunnisam** [nixgates/plugin.video.seren#802]
**Describe the bug**

seren causes kodi to crash and halt during playback of video.

**Log**

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/9067604/kodi.log)

**To Reproduce**

Steps to reproduce the behavior, for example:
1. Navigate to tv shows collection
2. Click on episode (play with seren or play with seren(smart play). any seren option  - same behaviour.
3. episode starts playback
4. Every day but not every episode, error occurs causing kodi to crash and exit

**Expected behavior**

TV Show playback continues as expected or it doesnt but kodi doesnt crash.

**Environment**

 - Operating System: openvix 6.2 (linux  4.4.35)
 - Kodi Version [e.g. 18.9, 19.1] : 20.0-ALPHA1 git 20220407
 - Seren Version [e.g. 2.1.3] 2.2.1
- python version: Python 3.10.4

**Screenshots and Additional Context**

**Comment by cbizzle14** [comment]
I've had this issue since they dropped 2.2 and I know it's Seren that's the problem. I disable Seren when I'm not gonna use it and kodi has never crashed since I've done that but once I re-enable it it will crash at some point. I just watched a movie and it crashed twice afterwards. I just reinstalled it to see if that fixes anything. Because it doesn't happen to my friend. We're both on Xbox Series X. Here's my log from a month ago

Https://paste.kodi.tv/abudapezon

**Comment by XSWG88** [comment]
This issue is based on syncing with Trakt but is an isolated Seren issue. The frequency seems to be attached to having Seren on multiple devices and having Trakt enabled on all of the devices. Haven't figured out a workaround yet other than removing Trakt from Seren that is install on non-primary devices. Not ideal but it's the only thing that limits the crashing.
