### ISSUE TITLE
[BUG]tmdb api key

### ISSUE THREAD

**Issue by Arthur1967** [nixgates/plugin.video.seren#808]
**Describe the bug** it's not really a bug but it won't except my API key for the movie database other add-ons do But they make you put in your username and password and then authenticate it from there in a session how do I get it to accept my API key thank you there is no log for this or I would've sent you one

**Log**

Please attach or link to and uploaded log file here.
Log files are required, and debug logs are preferable.
See the Kodi wiki for information on [how to get a log file](https://kodi.wiki/view/Log_file/Easy).

**To Reproduce**

Steps to reproduce the behavior, for example:

**Expected behavior**

**Environment**

 - Operating System
 - Kodi Version [e.g. 18.9, 19.1]
 - Seren Version [e.g. 2.1.3]

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.

**Comment by drinfernoo** [comment]
You just put a key in. For what it's worth, there is really no reason to use your own keys in the first place. The option is available in the event that Seren's keys stop working, but for now they are working fine, and using your own keys has no real benefit that I'm aware of.

If you've entered a valid key, and are getting errors, you can share a log file as required (and referred to in the issue template, which you've blatantly ignored), in order to help us diagnose the error.
