### ISSUE TITLE
Unwatched Shows in Collection to show only shows not started watching 

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#81]
Can you make it so the unwatched shows in collection section only displays shows in our collection we have not started to watch. 

This is really helpful if you use the Next Up widget to see your current episodes of your show to watch and also use the unwatched shows widget to show your shows you have added to collection but not started watching yet. 

Can it be a setting to enable or disable if possible in settings so we can filter out shows that are appearing in next up.

**Comment by nixgates** [comment]
I think what might be better served for this is if you utilized the Trakt Watchlist.

Rather than just throwing everything at your collection, if you add something to your Watchlist it will stay there until you have watched it once. This is almost exactly what you want, only difference is you will just need to add it to your collection should you decide you want to keep watching it 👍

**Comment by lukehansford** [comment]
What is the need to add it to your collection. Does it not move from the watchlist into the Seren Next up automatically?
