### ISSUE TITLE
[BUG] Still getting constant errors from Seren/Trakt

### ISSUE THREAD

**Issue by Madddcow** [nixgates/plugin.video.seren#810]
**Describe the bug**
Constant errors in the log re. Seren/Trakt connection

**Log**
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/9175569/kodi.log)

**Environment**

 - Nvidia Shield Pro 2019
 - Kodi Version v19.4
 - Seren Version v2.2.1

**Comment by whambulancePilot** [comment]
Your connection errors have to do with your device losing connectivity when sleeping and the fact the service sync still runs. Some people have issues losing connectivity when their device is sleeping and when their device wakes up with it taking a few extra seconds to gain connectivity.

The reason you don't see these with an addon forked from FEN is because it doesn't run the Trakt service sync when a device is sleeping. You'll have to kindly request Seren does something similar or disable sleep mode on your device.

**Comment by Madddcow** [comment]
Hmm, that’s really odd. I’ve only just reconfigured my Shield NOT to go to sleep.

**Comment by whambulancePilot** [comment]
Search for "sleep" (without quotes) in your log and you'll see it's still going to sleep. 

I'd double check your shield's settings and your Kodi power saving settings.

**Comment by drinfernoo** [comment]
Sorry it took so long, but this one should actually be addressed in Seren 2.2.2!
