### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by leemacca13** [nixgates/plugin.video.seren#833]
**Describe the bug**
Since the update to 2.2.2, next up doesn’t automatically refresh when an episode has been watched. Next up Widget is also not automatically updated and you now have to reload the skin to refresh the widget. The skin I am using is the latest version of Auramod. 

**To Reproduce**
Watch an episode of a tv show and when the episode ends the name of the episode remains in the next up list instead of disappearing. 

**Expected behavior**
Usually when an episode has been watched within a few seconds the episode is removed from the next up list and the widget refreshes to acknowledge this. 

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 19.4
 - Version 2.2.2

**Additional context**

**Comment by drinfernoo** [comment]
Please attach a debug log.

**Comment by TapMeDead** [comment]
@drinfernoo this thing with asking for logs has become too much, even made Venom quit because the dev was insane with anger over people not automatically providing a log. You don't need a log for this particular issue, it happens in every copy of Seren since the update. Watch a show with 2 unwatched episodes, scrollto the end of the first episode, and just watch as the popup does not come up.

**Comment by leemacca13** [comment]
Sorry, could you please explain how I can attach a debug log. Apologies I’ve never create d one before.

**Comment by TapMeDead** [comment]
@npmstart-pray you're right, I shouldn't have added that sentence, I was out of line, overly aggressive. I just happened to watch the chats between the 3 addons that quit a while back, Venom was one of them, and they were arrogant, treating their users pretty bad, to then shut down the public use of their addons because of it.
This of course does not apply to every dev, I am sorry for taking my opinion too far there.

**Comment by npmstart-pray** [comment]
If you feel like some penance is in order @TapMeDead , maybe post some instructions for @leemacca13 to help everyone ;)

**Comment by TapMeDead** [comment]
@npmstart-pray I see what you did there heh :) I am actually not sure how, with Seren, I can't find the debug tab in settings, I am assuming you mean the kodi.txt file?

**Comment by TapMeDead** [comment]
@npmstart-pray I added my own log of it in my own bug/issue report just below this one.

**Comment by drinfernoo** [comment]
@leemacca13 https://kodi.wiki/view/Log_file/Easy

@TapMeDead @npmstart-pray We require debug logs because they give detailed information about the user's environment, including the specific commit hash for the running build of Kodi, various debug information from Seren, and a handful of other things that aren't immediately obvious to a user (or to us) without looking at a log file.

We're not trying to be arrogant or catch other users' "mistakes", but often there's no point chasing issues we can't replicate ourselves (like this one), if there's no log for us to even start hunting from.
