### ISSUE TITLE
[REQUEST] Play Next not working Through Next Up as it used to.

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#878]
Nix, please make Play Next work as it used to through the Next Up window.
Refer to Issue #872 closed by drinfernoo.

**Comment by nixgates** [comment]
@TapMeDead have you recently reinstalled a fresh Kodi per chance?

Could you try enabling the following Kodi (not seren) setting.

Settings > Player > Videos > Play next video automatically

**Comment by cgwprs** [comment]
I was just about to upload my debug log for this.  The line I noticed in the log file says "python interpreter stopped" around the time stamp that the next episode did not play. The setting might be the problem though, new Kodi version (19.5) did not have anything selected for automatically play next... Thank you for looking into this.

**Comment by nixgates** [comment]
@cgwprs that line in the log is to be expected. 

@drinfernoo is correct in that Seren does not create a playliat automatically of the Next Up Menu. But, with the mentioned above setting, this can be achieved. That setting tells Kodi to load the current list of items into a playlist.

Serens playlisting is more context sensitive in which you can select any episode of an show and it will carry on playing that show and even traversing seasons until it reaches the last/latest episode. The kodi setting will only play what's in the list. 

The two settings can work together quite well though if that's how you wish to do it. 

There only caveat that I can think of is that mixed show lists like next up will act different to say a seasons episode list. 

If you are like me (to busy) and always a couple of episodes behind in a show, Seren will not play the next episodes for that show to the list and playback will confinue to the next show in next up. This is because Seren will not overwrite an existing playlist, only add to it if one exists and only add episodes for the current playing show once it reaches the last item of the list.

**Comment by TapMeDead** [comment]
> @TapMeDead have you recently reinstalled a fresh Kodi per chance?
> 
> Could you try enabling the following Kodi (not seren) setting.
> 
> Settings > Player > Videos > Play next video automatically

This is not an 'enable' setting, it pops up choices, and is currently set to "Episodes" here. Do I change it to one of the other choices? I believe this was the initial setting to make play next work, setting it to 'episodes' as it is now.

**Comment by cgwprs** [comment]
I enabled all of the choices in the "Play next video automatically" menu and the same thing happened. Three episodes played and then it stopped. 

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/10356793/kodi.log)

**Comment by nixgates** [comment]
@TapMeDead so I've just caught up with the team about this and it is a newer change in Seren that happened while I was away on a break. 

The change was brought about as another addon was causing issues across the board by modifying Kodi settings that would in turn cause issues in Seren. To resolve this issue, we had to ensure that the playlist consisted of what Seren was expecting. This meant removing excess shows, hence the issue you are seeing now.

Unfortunately, this is an edge case we hadn't considered as it was never an intended feature, more a happy coincidence. 

There is a workaround however. Disabling the Smart Play within Seren's settings and enable the above setting. This will work in place. The caveat with this is this will prevent Seren traversing seasons and the playlist will be constituted entirely of the menu that the item was played from. 

This however is likely almost exactly what you are used to and shouldn't cause you any issues. 

I will not with this as well, if you use the pre-scraping feature, ensure it is selected before you disable smart play. While disabling smart play will hide the setting, the state of the setting is still honored.

**Comment by TapMeDead** [comment]
I just tried all that, and it works from Next Up as usual now, at least for the testrun.
Thank you so much for looking into it, I watch something like 5-10 episodes every day from Next Up, just keeping up with aired episodes heh. So much easier just hitting enter and off we go to next item hehe.
Regards from Denmark.

**Comment by nixgates** [comment]
@TapMeDead not a problem, glad we could come to a resolution!
