### ISSUE TITLE
Nothing is playable in v0.2.6....Seren just sits there buffering

### ISSUE THREAD

**Issue by Madddcow** [nixgates/plugin.video.seren#91]
Hi there.  Since Seren auto-updated last night to v0.2.6, nothing is playable because Seren just sits there with 0% buffering at 3 secs into the video with no progress at all. It does this with every single show and movie I've tried.  The video will start playing and then stop at 3 secs with buffering sitting at 0%...it happens exactly the same way with every video. I've tried re-authorising Real Debrid and Trakt and this hasn't fixed it.  I regressed to v0.1.35 and the problem is still there. I uninstalled and reinstalled v0.2.6 and still nothing plays.  I've logged into Real Debrid and can successfully view the videos in the RD web browser, so the problem is definitely with Seren.  These issues have only started in the past 12 hours since Seren auto-updated to v0.2.6 as I'd been using the previous versions for months with no issues. My family used Seren about 8 times yesterday without problems until it auto-updated.  Now, nothing will play at all.

**Comment by trowieuk** [comment]
try providing the log...

**Comment by nixgates** [comment]
Howdy @Madddcow 

Buffering is 99.9% of the time due to your connection to the file. Not to say it couldn't be Seren, it's just the possibility of it causing buffering is near nothing.

Are you still having the issue? Is the issue only at certain times of the day? 

Unfortunately testing that a file can be watched from their website only proves that Kodi is having an issue viewing it and not Seren itself. 

Can you add a file to your RD cloud and try and play it from the My Files folder in Seren. This will cause a playback that Seren will not be involved in at all aside from passing the URL to Kodi. If this still has buffering then you can be pretty certain that the issue is outside of Seren.

**Comment by nixgates** [comment]
Closing issue due to lack of response from user
