### ISSUE TITLE
Next up functionality

### ISSUE THREAD

**Issue by ModMike** [nixgates/plugin.video.seren#911]
I did not want to post this as an issue because the problem could be between the chair and keyboard.

I am having a problem with Next Up. I want the system to show me all shows in my collection that have unwatched episodes.  Instead I get a complete history of every unwatched episode for any show I ever watched and long since dropped.

What am I (or Seren) doing wrong?

**Comment by npmstart-pray** [comment]
It's a trakt thing. Just go mark those series as watched (or un watched,if it was just a single episode or 3) and and they'll disappear. 
Up Next is for binge watching a la Netflix.

**Comment by ModMike** [comment]
I tried. I even paid fro VIP, can do anything.

**Comment by drinfernoo** [comment]
Next Up is not based on your Collection, it is based on your *History*. If there are shows in there that you don't want to see, you have three options:

* Mark the entire show as "unwatched"

This will reset your history for that show, which takes it out of the pool of shows you "are watching".

* Mark the entire show as "watched"

This indicates to Trakt that you have finished the show,  which takes it out of the pool of shows you "are watching".

* Hide the show

Open the context menu on a show item, choose "Trakt Manager", and then "Hide Show". This will give you the ability to *hide* the show from Next Up, while not affecting the actual watched *status*, according to Trakt.

The third option is, in my opinion, the most accurate way to go, since it will preserve which episodes you have and have not watched, but still allow you to "prune" your Next Up of shows which you don't intend to finish.
